export const initialState = {
  currentStep: parseInt(localStorage.currentStep) || 1,
  ticketQuantity: parseInt(localStorage.ticketQuantity) || 1,
  ticketType: localStorage.ticketType || "Regular",
  name: localStorage.name || "",
  email: localStorage.email || "",
  specialRequest: localStorage.specialRequest || "",
  imageLink: localStorage.imageLink || null,
  imageError: localStorage.imageError || null,
  nameError: localStorage.nameError || null,
  emailError: localStorage.emailError || null,
  loadingMessage: null,
  clickedButtonId: parseInt(localStorage.clickedButtonId) || 1,
  tickets: localStorage.tickets || [],
};
